enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
universal_ores = true
naturalist = true
consistency_plus = true
farmersdelight = true
seasonsextras = true
bountiful = true
forgottengraves = true
barteringstation = true
paladins = true
bedspreads = true
chipped = true
create = true
windchimes = true
extended_drawers = true
jmc = true
friendsandfoes = true
runes = true
plushies = true
minecraft = true
animal_feeding_trough = true
lootr = true
chalk = true
betterarcheology = true
bellsandwhistles = true
waystones = true
jewelry = true
railways = true
aurorasdeco = false
milk = true
beautify = true
tradingpost = true
betterpaths = true
archers = true
handcrafted = true
rocks = true
earthtojavamobs = true
lolmcv = true
extendedgears = true
villagersplus = true
abverticaledition = true
autopath = true
spell_engine = true
delightfulcreators = true
treechop = true
expandeddelight = true
furnish = true
azurelib = true
