name = "Amy's Optimized Vanilla Modpack"
author = "AmyFromEarth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a4905ab2697eba5420f85287499a96b82b625855f66947d883d127d9c419d72"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0"
