name = "Amy's Enhanced Vanilla Modpack"
author = "AmyFromEarth"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99061f0193195648ee405bb7f5732feb92faa3abc037bfb102d575f469d985a7"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
