name = "Amy's Awesome Vanilla Plus Modpack"
author = "AmyFromEarth"
version = "0.11.0 BETA"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46123f8ce33d849ddc620b25a8b9b993d5ecc5f9997d0be4754da3062f751e7d"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0"

[options]
datapack-folder = "datapacks"
