name = "Amy's Awesome Vanilla Plus Modpack"
author = "AmyFromEarth"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ae1ba32bc9c0167add5272f86ed3f423b50f013b9b490ab421b051c432ba738"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"

[options]
datapack-folder = "datapacks"
