name = "Amy's Awesome Vanilla Plus Modpack"
author = "AmyFromEarth"
version = "0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31066425311ee30e12be9bbe9e85ca383c726ec17dbe0d2b6d0a0525632866b7"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"

[options]
datapack-folder = "datapacks"
