name = "Amy's Awesome Vanilla Plus Modpack"
author = "AmyFromEarth"
version = "0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9bccba004b874ade9a893b9854d4c276c9706b2465e26d40a3073c814209e53"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"

[options]
datapack-folder = "datapacks"
