name = "Amy's Awesome Vanilla Plus Modpack"
author = "AmyFromEarth"
version = "0.10.0 KubeJS_Branch"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9beedb734ae10ced835aa13ea7b263dba27cf96fa67f2d05c45b87678777e3fb"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"

[options]
datapack-folder = "datapacks"
