name = "Amy's Awesome Vanilla Plus Modpack"
author = "AmyFromEarth"
version = "0.10.0 KubeJS_Branch"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9216526365d7424d8ffc62e1e7bcfa783c1de1ff5a4ef47862cdf7fbd4806d0"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"

[options]
datapack-folder = "datapacks"
