name = "Amy's Awesome Vanilla Plus Server Modpack"
author = "AmyFromEarth"
version = "0.4.0 KubeJS_Branch"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3b04e0e0e0f51f411345a4df7912e41ce04501c247bd23a09ec5a6544d7e2d6"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"

[options]
datapack-folder = "/datapacks"
