name = "Amy's Awesome Vanilla Plus Server Modpack"
author = "AmyFromEarth"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "976fea1bea4442cc5c07cdaf54b367a26f765c03bf6061d85f7eaf17cddba47e"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"

[options]
datapack-folder = "/datapacks"
