name = "Amy's Awesome Vanilla Plus Server Modpack"
author = "AmyFromEarth"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ecc6d68ea9769e250b7ae12d9854c2aa01a9b07b41ac7b36e41e6105b1baa4d"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"

[options]
datapack-folder = "/datapacks"
