name = "Amy's Awesome Vanilla Plus Server Modpack"
author = "AmyFromEarth"
version = "0.4.0 KubeJS_Branch"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "451b1fa1266f035e7b6a0f36849f4fb23c7a49362c116839db6925e0e701310e"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"

[options]
datapack-folder = "/datapacks"
